### ISSUE TITLE
Draw overlays below player or NPCs doesn't seem to work.

### ISSUE THREAD

**Issue by ulovemato111** [LeikvollE/tileindicators#12]
Draw overlays below player or NPCs doesn't seem to work, even after re-installing (The plugin) and/or restarting runelite
![Desktop](https://user-images.githubusercontent.com/105270939/167569656-09f3fbf4-0ea0-4b48-b28f-e5b7f87d697c.PNG)
.

**Comment by LeikvollE** [comment]
Do you have gpu enabled? The plugin only works when gpu is enabled.

**Comment by ulovemato111** [comment]
I did not have GPU enabled. All fixed now thank you. I hope thats not in a readme file because if it is i'm gonna feel really dumb.
Cheers
