### ISSUE TITLE
Enabling the Improved Tile Indicator plugin causes the prayer bar from the prayer plugin to render under the character.

### ISSUE THREAD

**Issue by derektedor** [LeikvollE/tileindicators#15]
Enabling the Improved Tile Indicator plugin causes the prayer bar from the prayer plugin to render under the character, instead of over like normal.

![image](https://user-images.githubusercontent.com/105892306/183789007-68f2776b-7e12-4948-a50d-c98cdab62927.png)

**Comment by LeikvollE** [comment]
Hmm, that is far from optimal. I recently updated the priority of the overlay so that it would properly draw all tiles below the player, however, I can see that it has had some unwanted side effects.

**Comment by Boreo** [comment]
Same issue with item drop texts.

Not sure how those would be solved, but definitely caused me to disable the plugin. Prayer bar is just too convenient.

**Comment by LeikvollE** [comment]
I think i actually managed to fix this problem(yay me!). It won't fix the issue with ground items though (at least not right now).  The change will probably be pushed to the plugin hub later this weekend together with some other fixes.

**Comment by LeikvollE** [comment]
This has now been fixed, and is live on the plugin hub
