### ISSUE TITLE
Destination tile style option not working nor available?

### ISSUE THREAD

**Issue by Nesslyn** [LeikvollE/tileindicators#16]
Was this option removed? I no longer see it in the plugin's configuration, nor does it work since its not there anymore when it previously was before the update D:

![OSRS 1](https://user-images.githubusercontent.com/111100389/184277628-2dc4d55f-cd0d-431a-b887-08d9082a9661.png)
The destination tile style option has poofed! Not there 

![OSRS 2](https://user-images.githubusercontent.com/111100389/184277637-7c517103-eb07-4e4e-9ba5-db791ae5336e.png)
The RS3 style destination style tile was my favorite option. Please fix and bring back, ty :)

**Comment by LeikvollE** [comment]
I am sorry, I was under the impression that no one was using it, so I removed it to simplify the code. However, given that this assumption was false I will look into ways to re-add it.

**Comment by Nesslyn** [comment]
Nnooo… DX 

Well while I can’t speak for everyone who uses this plugin? I certainly did use it. Made it much easier to know where my character was going to end up compared to using the other destination tile option in the plug-in that comes with Runlite. At least for me it did. Plus I like that it’s fancy looking instead of a plain colored bordered square. But okay! I’ll be looking forward to its return, if possible, tyvm :)

**Comment by Kinomora** [comment]
In the meantime, you can simply enable both Tile Indicators and Improved Tile Indicators to get the same functionality- as the other plugin has both the "Destination Tile" and "Hovered Tile" features, while Improved TI maintains the render layer fixes.

**Comment by Nesslyn** [comment]
That’s something I totally didn’t think of doing o.o I’ll do that in the meantime til the destination style option is brought back, maybe, hopefully, but til then? It can’t be helped

**Comment by DelVision** [comment]
Definitely would love to have the circular destination tile back, it was really good contrast difference with rest of the game

**Comment by dudeyourajerk** [comment]
Please revert the plugin to how it was a few weeks ago. I really miss the rs3 style destination. I definitely have been using this for a while despite the default plugin having similar functionality.

**Comment by Nesslyn** [comment]
He's going to look into ways it can be added again, he said. We be got to be patient and wait til then

**Comment by LeikvollE** [comment]
Ok, I have restored the code and have it up and running again in a way i am happy with(not yet pushed to the plugin hub). Seeing as you guys all use the custom destination indicators, is there something else you want fixed about it? Is the arrow icon the right size? Is it in the right location? Might as well fix such things at the same time if needed such that i don't spam the runlite team with plugin updates.

**Comment by Nesslyn** [comment]
Umm, it was perfect the way it was? But now that you mention it? I never noticed anything off with it after I began using it. Probably because I didnt take a closer look at it, you know? All I knew was that it appeared and worked exactly like the one RS3 has. So maybe get it as close to the one RS3 has as possible? Ty once more for this :D

**Comment by dudeyourajerk** [comment]
My only feedback would be the resolution of the arrow looks slightly less than the one in rs3. But not a big deal honestly.

**Comment by LeikvollE** [comment]
This has now been fixed and is live on the plugin hub. Thanks all for your feedback.
