### ISSUE TITLE
Draw overlays below NPCs strange behavior with Vardorvis

### ISSUE THREAD

**Issue by rednewt812** [LeikvollE/tileindicators#27]
Vardorvis appears to be using his hull rather than his outline when drawing the entity over indicators. This causes some strange behavior with indicators being hidden in incorrect places. 
The "ghost outline" appears to match the shape of his hull when enabled. 

<img width="257" alt="Screenshot 2023-08-09 100253" src="https://github.com/LeikvollE/tileindicators/assets/128299960/f953cf62-b7ee-4696-b7a4-3d2502ad701c">
<img width="241" alt="Screenshot 2023-08-09 100309" src="https://github.com/LeikvollE/tileindicators/assets/128299960/2fbe9f82-700a-4121-bc4f-b073a2a369db">
<img width="293" alt="Screenshot 2023-08-09 100615" src="https://github.com/LeikvollE/tileindicators/assets/128299960/6577dfb9-30f4-4a6d-8f0c-f7e61ac9d04c">

**Comment by LeikvollE** [comment]
What is your setup for the npc settings? Do you use the wildcard identifier "*", or have you added Vardorvis specifically?

**Comment by rednewt812** [comment]
> What is your setup for the npc settings? Do you use the wildcard identifier "*", or have you added Vardorvis specifically?

I normally use the wildcard, but testing it with both options has identical results. Tried different NPC limits, etc as well.

**Comment by LeikvollE** [comment]
I have found the cause and implemented a fix, will push to the plugin hub soon.
