### ISSUE TITLE
add option to remove the fill

### ISSUE THREAD

**Issue by thebubbsy** [LeikvollE/tileindicators#3]
as title says.
all tile marker types are filled with grey, allow us to remove that colour so its just the tile marker.

**Comment by LeikvollE** [comment]
Same thing as with the other issue. I will look at it, but don't have time until next week.

**Comment by Lipstopica** [comment]
@LeikvollE Is there any word on this? :( would really like for the fill to be changed please

**Comment by Lipstopica** [comment]
Awesome, thank you ^^

**Comment by LeikvollE** [comment]
Hello, I have now fixed this and pushed the code to GitHub. I will use the next couple of days to test and check that everything is good before pushing it to the plugin hub. Once i push to the pluginhub they usually have a wait time of 1 week to review changes, but this can both take longer or go faster depending on availability of reviewers.

**Comment by LeikvollE** [comment]
It should now be live on the plugin hub
