### ISSUE TITLE
Also draws player over ground item names

### ISSUE THREAD

**Issue by xHappyface** [LeikvollE/tileindicators#30]
Title says it all, this plugin draws the player over ground item names and is annoying as you cannot see item names when you are standing on the tile they are on or positioned in a way that your player blocks the item's name

**Comment by LeikvollE** [comment]
Unfortunately, this is not possible. The way ground item names are implemented, they are drawn below tile markers. Consequently, for the player to be drawn on top of tile markers, they also end up being drawn on top of ground item names.
