### ISSUE TITLE
add option to draw overlays below "player indicators"

### ISSUE THREAD

**Issue by DelVision** [LeikvollE/tileindicators#7]
I really like having player indicators to draw the tiles under players even while I have entity hider enabled.. So I know when there's players near me and where they are moving.

But in very crowded areas like wintertodt for example, the density of the players makes certain squares appear as basically black.. Which is a feature that I like to see the estimated amount of people there.. But it also hides my own character like shown in this image: 
![image](https://user-images.githubusercontent.com/34610275/149439047-67c8163d-da7f-471d-b4fb-d397aaff0149.png)

So if possible, it would be nice to have these indicators go behind the player just like the NPC indicators is already doing

![image](https://user-images.githubusercontent.com/34610275/149438984-b25bc6fb-e180-42d3-a1c1-96cb67ffc0a3.png)

Obviously I would prefer to only draw my own character above them when using entity hider, but if it's not too laggy.. It would be nice to have option to draw other players too above the indicators, but only as something you can toggle on and off because otherwise it would kinda remove the point of entity hider.

This should probably also apply to the list of NPC's that you have chosen to draw on top, so you could manually add all the pets to the same list too or any other NPC you want to be on top of the player tiles.

**Comment by DelVision** [comment]
It's working almost perfectly now, the only issue is that often it doesn't draw the player on top unless you restart the plugin

**Comment by LeikvollE** [comment]
This should be fixed in the latest update
